#!/usr/bin/env python3
"""
build_corpus_file.py -- NEEC: the corpus as one JSON file (neec_corpus.json, schema neec-corpus/1.0)
==================================================================================================
Session 30. neec_scores.csv does not carry the 26 criterion scores (see its data dictionary); they are
in the canonical script (SCORES) and in the summary block that ends each scoring document. This script
writes them, with each entry's short code and scope class, to neec_corpus.json:

  * keys, order and vectors  from the canonical script, neec_weighting_robustness_analysis_v2.py,
                             loaded through neec_entry.py (whose loader also checks the CSV rows);
  * display names            from neec_scores.csv;
  * codes and scope classes  from the summary blocks in the eleven scoring documents -- every block
                             must validate under neec_entry.py, and together they must cover every
                             canonical entry exactly once.

Uses: neec_entry.py --candidate reads the corpus's codes from it, so that a candidate's code can be
checked for uniqueness (protocol 9.3); and a blind replication kit carries a copy with the target
withheld, from which neec_entry.py reads the corpus when the canonical script is absent (protocol
section 11; build_replication_kit.py). Regenerated at every insertion, never edited by hand.

Usage:   python3 build_corpus_file.py
Inputs beside this script, else in the working directory. Writes neec_corpus.json; prints file names
only; deterministic. The rendering function, render(), is imported by build_replication_kit.py.
"""
import contextlib
import hashlib
import importlib.util
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = "neec_corpus.json"
SCHEMA_ID = "neec-corpus/1.0"
DOCUMENTS = (
    "NEEC_Step1c_Retrofit_C1_2ab_C1_5.md",
    "NEEC_Georgism_LVT_scoring_scratch.md",
    "NEEC_MutualCredit_LETS_scoring_scratch.md",
    "NEEC_DoughnutEconomics_scoring_scratch.md",
    "NEEC_UniversalBasicServices_scoring_scratch.md",
    "NEEC_SovereignWealthFundStatism_scoring_scratch.md",
    "NEEC_StateCapitalism_China_scoring_scratch.md",
    "NEEC_StateCapitalism_Singapore_scoring_scratch.md",
    "NEEC_StateCapitalism_Qatar_scoring_scratch.md",
    "NEEC_IslamicFinance_scoring_scratch.md",
    "NEEC_Ostrom_Commons_scoring_scratch.md",
)
DESCRIPTION = ("The canonical corpus of the NEEC Applied framework (v2 structure: 26 criteria in five domains): "
               "each entry's key, short code, display name, scope class (SCORING_PROTOCOL.md section 3) and "
               "criterion scores, in the canonical order. Generated by build_corpus_file.py from the canonical "
               "script (SCORES), neec_scores.csv (display names) and the summary blocks in the scoring documents "
               "(codes and scope classes); never edited by hand. Scores: 1.0 pass, 0.5 partial, 0.0 structural "
               "failure; totals, failures and tiers follow by protocol section 2.")


def locate(name):
    for d in (HERE, os.getcwd()):
        p = os.path.join(d, name)
        if os.path.isfile(p):
            return p
    sys.exit(f"ERROR: cannot find {name} beside this script or in the working directory")


def render(description, criteria, entries, extra=None):
    """The file's fixed layout: header fields, then one entry per line (a changed score is a one-line diff)."""
    head = {"schema": SCHEMA_ID, "description": description}
    head.update(extra or {})
    lines = ["{"]
    for k, v in head.items():
        lines.append(f"  {json.dumps(k)}: {json.dumps(v, ensure_ascii=False)},")
    lines.append(f'  "criteria": {json.dumps(criteria)},')
    lines.append('  "entries": [')
    for i, e in enumerate(entries):
        row = {"key": e["key"], "code": e["code"], "display_name": e["display_name"],
               "scope_class": e["scope_class"], "vector": {c: e["vector"][c] for c in criteria}}
        lines.append("    " + json.dumps(row, ensure_ascii=False) + ("," if i < len(entries) - 1 else ""))
    lines.append("  ]")
    lines.append("}")
    text = "\n".join(lines) + "\n"
    data = json.loads(text)
    if data["entries"] != [dict(key=e["key"], code=e["code"], display_name=e["display_name"],
                                scope_class=e["scope_class"], vector=e["vector"]) for e in entries]:
        raise AssertionError("render() does not round-trip")
    return text


def main():
    spec = importlib.util.spec_from_file_location("neec_entry", locate("neec_entry.py"))
    NE = importlib.util.module_from_spec(spec)
    with contextlib.redirect_stdout(io.StringIO()):
        spec.loader.exec_module(NE)
    if NE.CORPUS_SOURCE is not None:
        sys.exit("ERROR: the canonical script is not here; this builder writes the corpus from it")
    problems, found = [], {}
    for doc in DOCUMENTS:
        for b in NE.blocks_in_markdown(open(locate(doc), encoding="utf-8").read()):
            errs = NE.validate(b)
            if errs:
                problems.append(f"{doc}: [{b.get('code')}] {'; '.join(errs)}")
            elif b["key"] in found:
                problems.append(f"{doc}: [{b['code']}] {b['key']} already has a block in {found[b['key']][0]}")
            else:
                found[b["key"]] = (doc, b)
    missing = [k for k in NE.KEYS if k not in found]
    if missing:
        problems.append("no block for: " + ", ".join(missing))
    codes = [b["code"] for _d, b in found.values()]
    if len(codes) != len(set(codes)):
        problems.append("codes repeat across blocks")
    if problems:
        print("PROBLEMS (nothing written):")
        for p in problems:
            print(f"  - {p}")
        return 1
    entries = [{"key": k, "code": found[k][1]["code"], "display_name": NE.DISPLAY[k],
                "scope_class": found[k][1]["scope"]["class"], "vector": NE.SCORES[k]} for k in NE.KEYS]
    text = render(DESCRIPTION, NE.CRITS, entries)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    # read back through neec_entry's own corpus-file loader, and compare with the canonical corpus
    crits, scores, display, codes_by_key, classes = NE.load_corpus_file(OUT)
    assert crits == NE.CRITS and list(scores) == NE.KEYS and display == NE.DISPLAY
    assert all(abs(scores[k][c] - NE.SCORES[k][c]) < NE.EPS for k in NE.KEYS for c in NE.CRITS)
    tally = {}
    for e in entries:
        tally[e["scope_class"]] = tally.get(e["scope_class"], 0) + 1
    print("=" * 92)
    print(f"build_corpus_file.py -- {OUT} ({SCHEMA_ID})")
    print("=" * 92)
    print(f"canonical corpus: {NE.CANON_FILE}, {NE.CSV_FILE} ({len(NE.KEYS)} systems); "
          f"summary blocks read from {len(DOCUMENTS)} documents, all valid")
    for e in entries:
        s = NE.result(e["vector"])
        print(f"  {e['code']:5} {e['scope_class']:28} {NE.fmt(s['total']):>5}/26 {s['failures']:2d}  {e['display_name']}")
    print("scope classes: " + ", ".join(f"{k} {tally[k]}" for k in NE.SCOPE_CLASSES if k in tally))
    print(f"wrote {OUT} (md5 {hashlib.md5(text.encode('utf-8')).hexdigest()[:8]}); "
          f"read back by neec_entry.load_corpus_file: identical to the canonical corpus")
    return 0


if __name__ == "__main__":
    sys.exit(main())
