"""criteria_v2_s45.py - evidence tables for NEEC_Criteria_v2_s45.md (Session 45; Package C, decision 46.1, added in
Session 46: the section 2 header counts criteria instead of stating them, and section 4 registers Package C's
quantities, as build_criteria.py version 2.1 does; decision 47.1, Session 47, adds section 5).

Reads, beside this script: criteria_s44_snapshot.json (the 26 criteria as they stood at tag s44),
criteria.json (the v2.0 criteria, generated by build_criteria.py version 2), NEEC_Criteria_v2_s45.md (its
Appendix V, for the declared descriptive figures) and neec_corpus.json, and, for section 5, wjp_rol_sf62_2012_2025.csv (md5 checked). Changes nothing. Prints:
  1. the figure scan behind the record's section 3: figures in a Requirement or measurement field that the
     criterion's Pass Threshold lacks, on the s44 criteria (each hit classed, and the classes asserted) and on
     v2.0 (asserted: no Requirement figure, and only declared descriptive figures elsewhere);
  2. the implicit weight of each norm N1-N14 under equal criterion weighting, s44 against v2.0;
  3. the units the rescoring pass treats, by revision class and published score, and the new units;
  4. the registered quantities and the Pass Thresholds that carry each, s44 against v2.0;
  5. C4.6 clause 3's bar (decision 47.1): the upper quartile of the World Justice Project Rule of Law Index's
     sub-factor 6.2 in its 2025 edition, on both quartile definitions, and in every edition; the jurisdictions that
     meet it; the reference economies of the corpus's configured national economies; and the range of bars that
     gives them the same verdicts. Each figure the record states is asserted.
The figure rule is the one build_criteria.py asserts as A1 (same patterns). Deterministic.
"""
import csv
import hashlib
import json
import os
import re
import statistics
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))


def load(name):
    with open(os.path.join(HERE, name), encoding="utf-8") as f:
        return f.read() if name.endswith(".md") else json.load(f)


old, new, corpus = load("criteria_s44_snapshot.json"), load("criteria.json"), load("neec_corpus.json")["entries"]
record = load("NEEC_Criteria_v2_s45.md")
OLD = {c["id"]: c for c in old["criteria"]}
NEW = {c["id"]: c for c in new["criteria"]}
print("Inputs: criteria_s44_snapshot.json, criteria.json, NEEC_Criteria_v2_s45.md, neec_corpus.json, "
      "wjp_rol_sf62_2012_2025.csv")
print(f"Criteria: {len(OLD)} at s44, {len(NEW)} in v2.0; corpus entries: {len(corpus)} (vectors in force, on the "
      "s44 criteria, before the rescoring pass is applied)\n")

# ---------------------------------------------------------------- 1. figure scan (build_criteria.py rule A1)
REFS = re.compile(r"\bC\d\.\d[ab]?\b|\bN\d+\b|\b[DKRGS]\d+\b|\bCO2\b|COVID-19|rtfpna|\bv\d\.\d\b"
                  r"|(?:[Ss]ection|protocol|Appendix|Paper [Ss]ection) [A-Z]?\.?\d+(?:\.\d+)*(?:\([a-g]\))?"
                  r"|SDG(?: indicator)? \d+(?:\.\d+)+|SNA item D\.\d+"
                  r"|[Cc]lauses? \d+(?:\s*(?:\u2013|-|and|,)\s*\d+)*")
NUM = re.compile(r"\$?\d[\d,]*(?:\.\d+)?%?")
FIELDS = ("requirement", "measurement", "measurement_protocol", "cultural_geographic_adaptation")


def figures(text):
    return [n.rstrip(",") for n in NUM.findall(REFS.sub(" ", text))]


def scan(crit):
    hits = {}
    for cid, c in crit.items():
        d = c["definition"]
        pt = set(figures(d["pass_threshold"]))
        for f in FIELDS:
            extra = [n for n in figures(d.get(f, "")) if n not in pt]
            if extra:
                hits[(cid, f)] = extra
    return hits


S44_CLASS = {
    ("C1.1", "requirement"): "K6 known (review): the aspirational 95% requirement",
    ("C1.1", "measurement_protocol"): "descriptive: the reduction formula and 5-year tracking",
    ("C1.2a", "requirement"): "K6 known (review): $70,000+ against >=$60,000",
    ("C1.2a", "cultural_geographic_adaptation"): "K6 known (review): the field is removed in v2.0",
    ("C1.3", "requirement"): "K6 new (Session 45): 90%+ against >=88%",
    ("C1.4", "requirement"): "descriptive: the displacement shares, the threshold's scope in v2.0",
    ("C1.4", "measurement"): "K6 known (review): dated scenarios, poverty <5-10%, demand 80-110%",
    ("C3.3", "measurement"): "K6 new (Session 45): per-function figures against degradation <20%",
    ("C4.1", "requirement"): "K3: the carbon range, measured once, in C4.2, in v2.0",
    ("C4.1", "measurement"): "K3 (carbon figures) and K6 new (Session 45): debt <60% against <80%",
    ("C5.1", "requirement"): "K6 new (Session 45): 40+ years preferred against >=20",
    ("C5.3", "measurement"): "descriptive: simulation scale; the criterion is unchanged",
}
h44 = scan(OLD)
assert set(h44) == set(S44_CLASS), f"s44 scan hits changed: {sorted(set(h44) ^ set(S44_CLASS))}"
print("1. Figures in a Requirement or measurement field that the Pass Threshold lacks")
print("   (a) The s44 criteria")
for (cid, f), figs in h44.items():
    print(f"     {cid:<6}{f:<31}{S44_CLASS[(cid, f)]}")
    print(f"     {'':<37}figures: {', '.join(figs)}")
new_k6 = sorted({cid for (cid, f), lab in S44_CLASS.items() if "K6 new" in lab})
known = sorted({cid for (cid, f), lab in S44_CLASS.items() if "K6 known" in lab})
assert new_k6 == ["C1.3", "C3.3", "C4.1", "C5.1"] and known == ["C1.1", "C1.2a", "C1.4"]
print(f"     Gaps the review listed (K6): {', '.join(known)}. Gaps it missed: {', '.join(new_k6)}.")

allow = {}
cur = None
for line in record[record.index("## Appendix V."):].split("\n"):
    m = re.match(r"^### (C\d\.\d[ab]?)", line)
    if m:
        cur = m.group(1)
    a = re.match(r"^- \*\*allow\*\*: (.*)$", line)
    if a and cur:
        allow[cur] = {x.strip() for x in re.split(r",\s+", a.group(1)) if x.strip()}
h2 = scan(NEW)
assert not [k for k in h2 if k[1] == "requirement"], "a v2.0 Requirement carries a figure its threshold lacks"
assert all(set(v) <= allow.get(k[0], set()) for k, v in h2.items()), "an undeclared v2.0 measurement figure"
print("   (b) The v2.0 criteria: no Requirement carries a figure its Pass Threshold lacks; the remaining")
print("       measurement figures are each declared descriptive in the criterion's Appendix V block")
for (cid, f), figs in h2.items():
    print(f"     {cid:<6}{f:<31}{', '.join(figs)}")
print()

# ---------------------------------------------------------------- 2. implicit norm weights
def norm_weights(crit):
    names, weight, count = {}, {}, {}
    for c in crit.values():
        found = re.findall(r"N(\d+) \(([^)]+)\)", c["definition"]["derivation"])
        norms = sorted({int(n) for n, _ in found})
        for n, label in found:
            names.setdefault(int(n), label.split(" and ")[0] if int(n) == 7 else label)
        for n in norms:
            weight[n] = weight.get(n, 0) + 1 / len(norms)
            count[n] = count.get(n, 0) + 1
    return names, weight, count


n1, w1, k1 = norm_weights(OLD)
n2, w2, k2 = norm_weights(NEW)
names = {**n1, **n2}
print("2. Implicit norm weights under equal criterion weighting (each criterion's weight split equally among")
print(f"   its derivation norms), s44 ({len(OLD)} criteria) against v2.0 ({len(NEW)})")
print(f"   {'Norm':<32}{'s44 crit':>9}{'share':>8}{'v2.0 crit':>10}{'share':>8}{'change':>9}")
for n in sorted(set(w1) | set(w2), key=lambda k: (-w2.get(k, 0), k)):
    s1, s2 = w1.get(n, 0) / len(OLD), w2.get(n, 0) / len(NEW)
    print(f"   N{n:<3}{names[n]:<28}{k1.get(n, 0):>9}{s1:>8.1%}{k2.get(n, 0):>10}{s2:>8.1%}{(s2 - s1) * 100:>+8.1f}pp")
hi1, lo1 = max(w1.values()) / len(OLD), min(w1.values()) / len(OLD)
hi2, lo2 = max(w2.values()) / len(NEW), min(w2.values()) / len(NEW)
print(f"   Range: s44 {lo1:.1%} to {hi1:.1%} (ratio {hi1 / lo1:.1f}); v2.0 {lo2:.1%} to {hi2:.1%} (ratio {hi2 / lo2:.1f})")
print(f"   Norms with no criterion: s44 {[n for n in range(1, 15) if n not in w1] or 'none'}; "
      f"v2.0 {[n for n in range(1, 15) if n not in w2] or 'none'}")
assert set(w2) == set(range(1, 15)), "a norm has no v2.0 criterion"
print()

# ---------------------------------------------------------------- 3. units by revision class
SCOPE = Counter(e["scope_class"] for e in corpus)
print("3. Units the rescoring pass treats (an entry's score on a criterion), by v2.0 revision class and the")
print("   score in force (Paper v1.4 criteria, with the pass's recorded re-estimates not yet applied)")
print(f"   Corpus: {len(corpus)} entries (" + ", ".join(f"{v} {k.replace('_', ' ')}" for k, v in sorted(SCOPE.items()))
      + ")")
print(f"   {'class':<7}{'criteria':>9}{'units':>7}{'1.0':>6}{'0.5':>6}{'0.0':>6}   meaning")
tot_units = 0
for cls, meaning in new["classes"].items():
    ids = [c["id"] for c in new["criteria"] if c["revision"]["cls"] == cls]
    sc = Counter(e["vector"][cid] for cid in ids if cid in OLD for e in corpus)
    units = len(ids) * len(corpus)
    tot_units += units
    cells = ("  new " * 3) if cls == "N" else f"{sc[1.0]:>6}{sc[0.5]:>6}{sc[0.0]:>6}"
    print(f"   {cls:<7}{len(ids):>9}{units:>7}{cells}   {meaning}: {', '.join(ids)}")
assert tot_units == len(NEW) * len(corpus)
ids_i = [c["id"] for c in new["criteria"] if c["revision"]["cls"] == "I"]
cne = [e for e in corpus if e["scope_class"] == "configured_national_economy"]
ids_d = [c["id"] for c in new["criteria"] if c["revision"]["cls"] == "D"]
d_half = sum(e["vector"][cid] == 0.5 for cid in ids_d for e in corpus)
n_new = sum(1 for c in new["criteria"] if c["revision"]["cls"] == "N") * len(corpus)
print(f"   Class I units on configured national economies, where a named indicator is a published series: "
      f"{len(ids_i) * len(cne)} ({len(ids_i)} criteria x {len(cne)} entries)")
print(f"   Class D units at 0.5, which can rise when a deleted clause was the only one not shown: {d_half}")
print(f"   New units (class N): {n_new}")
print()

# ---------------------------------------------------------------- 4. registered quantities
QUANTITIES = {
    "wealth Gini": r"\bGini\b", "citizen proposals adopted": r"proposals", "carbon": r"carbon|CO2",
    "resource use against regeneration": r"regenerat|biocapacity", "autonomy share": r"autonomy|coercion",
    "association": r"association|[Cc]ivil-liberties", "housing stability": r"housing stability",
    "public debt": r"\b[Dd]ebt\b", "productivity": r"per hour|productivity", "inflation": r"inflation",
    "medical consent and compulsion": r"consent|compulsory", "pollution mortality": r"pollution",
    "liability for harm": r"liable|liability", "regulatory independence": r"improper influence"}
print("4. Registered quantities (build_criteria.py rule A2) and the Pass Thresholds that carry each")
print(f"   {'quantity':<36}{'s44':<20}v2.0")
for q, pat in QUANTITIES.items():
    a = [cid for cid, c in OLD.items() if re.search(pat, c["definition"]["pass_threshold"])]
    b = [cid for cid, c in NEW.items() if re.search(pat, c["definition"]["pass_threshold"])]
    assert len(b) == 1
    print(f"   {q:<36}{', '.join(a) or '(none)':<20}{', '.join(b)}")
dup = [q for q, pat in QUANTITIES.items()
       if sum(bool(re.search(pat, c["definition"]["pass_threshold"])) for c in OLD.values()) > 1]
assert "Gini clause removed" in OLD["C1.5"]["definition"]["pass_threshold"]
print("   (C1.5's s44 threshold names the Gini only in a parenthesis recording its removal; v2.0 moves that\n"
      "   commentary out of the threshold, class W.)")
print(f"   Carried by more than one s44 threshold: {len(dup)} ({', '.join(dup)}); in v2.0: none")
print()

# ---------------------------------------------------------------- 5. C4.6 clause 3 bar (decision 47.1)
WJP, WJP_MD5 = "wjp_rol_sf62_2012_2025.csv", "a636d6a2d9cf0b0f190825e6c10f1cbd"
with open(os.path.join(HERE, WJP), "rb") as f:
    raw = f.read()
assert hashlib.md5(raw).hexdigest() == WJP_MD5, "the WJP extract is not the one decision 47.1 read"
wjp = {}
for r in csv.DictReader(raw.decode("utf-8").splitlines()):
    wjp.setdefault(r["edition"], {})[r["code"]] = (r["jurisdiction"], float(r["sf62"]))
BAR = 0.77
print("5. C4.6 clause 3 bar (decision 47.1): World Justice Project Rule of Law Index, sub-factor 6.2")
print(f"   Source: {WJP} (md5 {WJP_MD5[:8]}), extracted from the 2025 edition's historical data file\n"
      "   (2025_wjp_rule_of_law_index_HISTORICAL_DATA_FILE.xlsx, md5 56724a01), sheet 'Historical Data'; "
      f"{sum(len(v) for v in wjp.values())} scores")
print(f"   {'edition':<11}{'jurisdictions':>14}{'median':>8}{'Q3 incl.':>10}{'Q3 excl.':>10}")
q3 = {}
for ed in sorted(wjp):
    v = sorted(x for _, x in wjp[ed].values())
    qi, qe = (statistics.quantiles(v, n=4, method=m) for m in ("inclusive", "exclusive"))
    q3[ed] = (qi[2], qe[2], len(v))
    print(f"   {ed:<11}{len(v):>14}{qi[1]:>8.3f}{qi[2]:>10.4f}{qe[2]:>10.4f}")
cur = wjp["2025"]
qi, qe, n25 = q3["2025"]
assert n25 == 143 and round(qi, 4) == 0.7665 and round(qe, 4) == 0.7712
assert round(qi, 2) == round(qe, 2) == BAR
assert all(0.75 <= round(q3[ed][0], 2) <= 0.78 for ed in q3 if ed >= "2014")
assert round(q3["2012-2013"][0], 2) == 0.73 and q3["2012-2013"][2] == 97
meet = [c for c, (_, x) in cur.items() if round(x, 2) >= BAR]
assert len(meet) == 36
med = statistics.median(x for _, x in cur.values())
print(f"   2025: upper quartile {qi:.4f} (inclusive) and {qe:.4f} (exclusive), {BAR} on both; median {med:.4f}; "
      f"{len(meet)} of {n25} jurisdictions score {BAR} or more at two decimals")
print("   Upper quartile, editions 2014 to 2025: "
      f"{min(round(q3[e][0], 2) for e in q3 if e >= '2014'):.2f} to {max(round(q3[e][0], 2) for e in q3 if e >= '2014'):.2f}")
REF = [("SQ", "USA"), ("NSD", "DNK"), ("NSD", "FIN"), ("NSD", "NOR"), ("NSD", "SWE"), ("SG", "SGP"), ("QA", "QAT"),
       ("CN", "CHN")]
cne = {e["code"] for e in corpus if e["scope_class"] == "configured_national_economy"}
assert {k for k, _ in REF} | {"CPS"} == cne
print("   Reference economies of the configured national economies, 2025 edition (indicative: no C4.6 unit is scored")
print("   before stage 2, on each entry's stated date and configuration):")
got = {}
for k, c in REF:
    name, x = cur[c]
    got[c] = round(x, 2)
    print(f"     {k:<4}{name:<16}{x:.4f}  {got[c]:.2f}  {'meets' if got[c] >= BAR else 'does not meet'} {BAR}")
assert got == {"USA": 0.87, "DNK": 0.97, "FIN": 0.97, "NOR": 0.99, "SWE": 0.92, "SGP": 0.94, "QAT": 0.66, "CHN": 0.61}
absent = [c for c in ("ISL", "CUB", "PRK", "SUN", "RUS") if c not in cur]
assert absent == ["ISL", "CUB", "PRK", "SUN"]
print("     CPS not in the Index: the Soviet Union, Cuba and North Korea (nor is Iceland, of the Nordic economies)")
same = [b / 100 for b in range(1, 100) if all((got[c] >= b / 100) == (got[c] >= BAR) for c in got)]
assert (min(same), max(same)) == (0.67, 0.87)
at_med = [c for c in got if got[c] >= round(med, 2)]
assert round(med, 2) == 0.61 and "QAT" in at_med and "CHN" in at_med
print(f"   Bars giving these eight the same verdicts: {min(same):.2f} to {max(same):.2f}; at the median "
      f"({round(med, 2):.2f}) all eight meet it")
