#!/usr/bin/env python3
"""
verify_insertion_s25.py -- NEEC Session 25: verify the third consolidated insertion
===================================================================================
Checks the result of insert_session25.py end to end, on the live files:

  (1) SOURCES      each new vector, AST-extracted from its verifier, re-sums to the
                   summary its own scratch document states (and, for Qatar, to
                   verify_qatar.py's PUBLISHED)
  (2) CANONICAL    the live script vs the extracted vectors and the pinned Session 20
                   snapshot: 20 earlier vectors and PUBLISHED entries unchanged; key
                   order = snapshot + Qatar, Islamic finance, Ostrom; helpers unchanged
  (3) CSV          regenerated by the live builder; header + 20 rows byte-identical to
                   the Session 20 CSV; the three new rows match their vectors
  (4) GENERATOR    insert_session25.py reproduces both live scripts byte for byte, and
                   REFUSES corrupted input (a document's domain line, the snapshot, a
                   vector) -- negative tests
  (5) CLAIMS       every claim in the three row notes and in the new `pairs` comment:
                   the claim's text must appear, and the fact it states must hold
                   (decision D3(b): comparative claims are asserted, not only printed)
  (6) STEP 5       the combined 23-system reference facts Step 5's prose will draw on,
                   including the CCO-PTF-CIP-SZH escape table and the frontier
                   identity (decision D11), each asserted; then printed as tables

Every count is computed from the corpus; the expected values are written here so
that any change to the data fails loudly rather than silently re-printing.

Usage:   python3 verify_insertion_s25.py
Exit status is 0 only if every check passes. Output is deterministic (file names
only, no paths).
"""
import ast
import csv
import hashlib
import importlib.util
import io
import os
import re
import shutil
import subprocess
import sys
import tempfile
from itertools import combinations

HERE = os.path.dirname(os.path.abspath(__file__))
CANON = "neec_weighting_robustness_analysis_v2.py"
BUILDER = "neec_scores_csv_builder_v2.py"
CSV = "neec_scores.csv"
BASELINE = "baseline_weighting_script.py"
GEN = "insert_session25.py"
SNAP = {CANON: ("neec_weighting_robustness_analysis_v2_s20_snapshot.py", "487d5a94138f3f896c3f723498b6c0e9"),
        BUILDER: ("neec_scores_csv_builder_v2_s20_snapshot.py", "5f547d0dcc44024b31629ffcf564453d"),
        CSV: ("neec_scores_s20_snapshot.csv", "0630f8828d688a7dcc85800fcebda463")}

D1 = ['C1.1', 'C1.2a', 'C1.2b', 'C1.3', 'C1.4', 'C1.5']
DOMAINS = [D1] + [[f'C{d}.{i}' for i in range(1, 6)] for d in range(2, 6)]
ALL = [c for g in DOMAINS for c in g]
DOMAIN_NAMES = ["Material Security", "Human Autonomy", "System Resilience",
                "Ethical Integrity", "Implementation Viability"]

QA, IF, OS = 'State Capitalism / Qatar', 'Islamic Finance / Profit-Sharing Banking', 'Ostrom-Style Commons Governance'
CCO, SG, CN, SWF = 'CCO-PTF-CIP-SZH', 'State Capitalism / Singapore', 'State Capitalism / China', 'Sovereign Wealth Fund Statism'
SQ, LM, STK = 'Status Quo Market Capitalism', 'Libertarian Minarchism', 'Stakeholder Capitalism'
GEO, UBS, MC, PE = 'Georgism / Land Value Tax', 'Universal Basic Services', 'Mutual Credit / LETS', 'Participatory Economics'
NEW = {QA: ('verify_qatar.py', 'QA', 'NEEC_StateCapitalism_Qatar_scoring_scratch.md',
            'State Capitalism / Qatar (Gulf Rentier-Distributive Statism)'),
       IF: ('verify_islamicfinance.py', 'SCORE', 'NEEC_IslamicFinance_scoring_scratch.md', IF),
       OS: ('verify_ostrom.py', 'OSTROM', 'NEEC_Ostrom_Commons_scoring_scratch.md', OS)}
STEP1B = [GEO, MC, 'Doughnut Economics', UBS, SWF, CN, SG, QA, IF, OS]   # scoring order, Sessions 6-23

RESULTS = []


def check(label, cond):
    RESULTS.append(bool(cond))
    print(f"  {'PASS' if cond else 'FAIL'}  {label}")


def path(name):
    return os.path.join(HERE, name)


def read(name):
    with open(path(name), encoding="utf-8") as f:
        return f.read()


def md5(name):
    with open(path(name), "rb") as f:
        return hashlib.md5(f.read()).hexdigest()


def module_literal(text, var):
    hits = [ast.literal_eval(n.value) for n in ast.parse(text).body if isinstance(n, ast.Assign)
            and any(getattr(t, "id", None) == var for t in n.targets)]
    if len(hits) != 1:
        raise SystemExit(f"ERROR: expected one module-level {var}, found {len(hits)}")
    return hits[0]


def load(name, modname):
    spec = importlib.util.spec_from_file_location(modname, path(name))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def sums(v):
    return [sum(v[c] for c in g) for g in DOMAINS]


def total(v):
    return sum(v[c] for c in ALL)


def fails(v):
    return [c for c in ALL if v[c] == 0.0]


def tier(n):
    return ('Potentially Adequate' if n <= 2 else 'Partially Adequate' if n <= 5 else 'Structurally Inadequate')


def moved(v, changes):
    w = dict(v)
    w.update(changes)
    return w


def higher(a, b):
    return [c for c in ALL if a[c] > b[c]]


def dominates(a, b):
    return all(a[c] >= b[c] for c in ALL) and any(a[c] > b[c] for c in ALL)


def enumerate_flags(v, flags):
    """Every combination of flagged calls (each at its scored value or its stated alternative).
    Returns (n_combinations, min total, max total, {tier: count}). Each flag is on its own
    criterion, so total and failure count are additive: counted exactly by convolution."""
    dist = {(0.0, 0): 1}
    for c, alt in flags.items():
        dt, df = alt - v[c], (alt == 0.0) - (v[c] == 0.0)
        new = {}
        for (t, f), n in dist.items():
            for key in ((t, f), (t + dt, f + df)):
                new[key] = new.get(key, 0) + n
        dist = new
    base_t, base_f = total(v), len(fails(v))
    tiers = {}
    for (t, f), n in dist.items():
        tiers[tier(base_f + f)] = tiers.get(tier(base_f + f), 0) + n
    return (sum(dist.values()), base_t + min(t for t, _ in dist), base_t + max(t for t, _ in dist), tiers)


print("=" * 96)
print("verify_insertion_s25.py -- NEEC Session 25: third consolidated insertion (20 -> 23 systems)")
print("=" * 96)

# ---------------------------------------------------------------------------- (1)
print("\n(1) SOURCES: vectors AST-extracted from the Step 1b verifiers, against their documents")
TOTAL_RE = re.compile(r'^\*\*(?:Total|Overall Score): (\d+\.\d)/26 \((\d+(?:\.\d)?)%\)')
EXTRACTED = {}
for key, (src, var, doc, _) in NEW.items():
    v = module_literal(read(src), var)
    EXTRACTED[key] = v
    lines = read(doc).split("\n")
    hits = [i for i, x in enumerate(lines) if TOTAL_RE.match(x)]
    stated_dom = []
    for name in DOMAIN_NAMES:
        rx = re.compile(r'^(?:\| |- )' + re.escape(name) + r'(?: \| |: )(\d+\.\d)\b')
        stated_dom.append([float(rx.match(x).group(1)) for x in lines[max(0, hits[0] - 24):hits[0]] if rx.match(x)])
    blob = " ".join(" ".join(lines[hits[0]:hits[0] + 9]).split())
    fm = re.search(r'Structural failures: (\d+) \(', blob) or re.search(r'and (\d+) at 0\.0', blob)
    check(f"{var} ({src}): 26 criteria in canonical order; re-sums to the domain totals, total and "
          f"failure count stated in {doc}",
          list(v) == ALL and len(hits) == 1 and [x[0] for x in stated_dom if len(x) == 1] == sums(v)
          and float(TOTAL_RE.match(lines[hits[0]]).group(1)) == total(v) and int(fm.group(1)) == len(fails(v)))
qp = module_literal(read('verify_qatar.py'), 'PUBLISHED')
check("Qatar also matches verify_qatar.py's PUBLISHED (domains, total, 35%, 10 failures, tier)",
      [qp[f'D{i}'] for i in range(1, 6)] == sums(EXTRACTED[QA]) and qp['Total'] == 9.0 and qp['Percent'] == 35
      and qp['Failures'] == 10 and qp['Tier'] == 'Structurally Inadequate')

# ---------------------------------------------------------------------------- (2)
print("\n(2) CANONICAL SCRIPT: live file vs the extracted vectors and the Session 20 snapshot")
for live_name, (snap_name, digest) in SNAP.items():
    check(f"{snap_name} is the pinned Session 20 file (md5 {digest[:8]})", md5(snap_name) == digest)
buf = io.StringIO()
live = load(CANON, "live")
s20 = load(SNAP[CANON][0], "s20")
check("verify_transcription() passes for all 23 systems", live.verify_transcription(verbose=False))
sys.stdout, saved = buf, sys.stdout
try:
    legacy_ok = live.verify_unchanged_from_legacy(path(BASELINE), verbose=False)
finally:
    sys.stdout = saved
check("verify_unchanged_from_legacy() passes (13 retrofitted systems)", legacy_ok and buf.getvalue() == "")
S = live.SCORES
check("Canonical SCORES holds exactly 23 systems", len(S) == 23)
check("Key order: the 20 snapshot systems, then Qatar, Islamic finance, Ostrom",
      list(S) == list(s20.SCORES) + [QA, IF, OS])
check("PUBLISHED has the same 23 keys in the same order", list(live.PUBLISHED) == list(S))
check("All 20 earlier vectors are identical to the snapshot's",
      all(S[k] == s20.SCORES[k] and list(S[k]) == list(s20.SCORES[k]) for k in s20.SCORES))
check("All 20 earlier PUBLISHED entries are identical to the snapshot's",
      all(live.PUBLISHED[k] == s20.PUBLISHED[k] for k in s20.PUBLISHED))
for key in NEW:
    d = sums(EXTRACTED[key])
    check(f"{key}: canonical vector == extracted vector; PUBLISHED == its domain sums and total",
          S[key] == EXTRACTED[key] and list(S[key]) == ALL
          and live.PUBLISHED[key] == {'D1': d[0], 'D2': d[1], 'D3': d[2], 'D4': d[3], 'D5': d[4], 'Total': sum(d)})
check("ALL_CRITS, D1_CRITS, D5_CRITS, PUBLISHED_LEGACY_25 and the four SCHEMES unchanged",
      (live.ALL_CRITS, live.D1_CRITS, live.D5_CRITS, live.PUBLISHED_LEGACY_25) ==
      (s20.ALL_CRITS, s20.D1_CRITS, s20.D5_CRITS, s20.PUBLISHED_LEGACY_25) and live.SCHEMES == s20.SCHEMES)


def pairs_literal(text):
    found = [ast.literal_eval(n.value) for n in ast.walk(ast.parse(text)) if isinstance(n, ast.Assign)
             and any(getattr(t, "id", None) == "pairs" for t in n.targets)]
    return found[0] if len(found) == 1 else None


NEW_PAIRS = [(IF, GEO), (IF, UBS), (IF, STK), (OS, SWF), (OS, SG), (OS, IF), (SG, QA), (CN, QA),
             (CCO, QA), (CCO, IF), (CCO, OS)]
check("The spot-check `pairs` list is the snapshot's 16 pairs followed by the 11 Session 25 pairs",
      pairs_literal(read(CANON)) == pairs_literal(read(SNAP[CANON][0])) + NEW_PAIRS
      and len(pairs_literal(read(SNAP[CANON][0]))) == 16)

# ---------------------------------------------------------------------------- (3)
print("\n(3) CSV: regenerated by the live builder; prefix identical to the Session 20 CSV")
with tempfile.TemporaryDirectory() as tmp:
    for name in (CANON, BUILDER):
        shutil.copy(path(name), tmp)
    proc = subprocess.run([sys.executable, BUILDER], cwd=tmp, capture_output=True)
    check("Live builder runs cleanly (its own cross-validation passes)",
          proc.returncode == 0 and b"Cross-validation PASSED: all 23 systems" in proc.stdout)
    with open(os.path.join(tmp, CSV), "rb") as f:
        regenerated = f.read()
live_csv = open(path(CSV), "rb").read()
snap_csv = open(path(SNAP[CSV][0]), "rb").read()
check("Regenerated CSV is byte-identical to the live neec_scores.csv", regenerated == live_csv)
check("Header and first 20 rows byte-identical to the Session 20 CSV",
      live_csv.splitlines(keepends=True)[:21] == snap_csv.splitlines(keepends=True) and len(snap_csv.splitlines()) == 21)
rows = list(csv.reader(io.StringIO(live_csv.decode("utf-8"))))
check("CSV has a header plus exactly 23 rows, 14 columns each", len(rows) == 24 and all(len(r) == 14 for r in rows))
names_map = module_literal(read(BUILDER), "csv_names_to_published")
NOTES = {}
for key, (_, _, _, display) in NEW.items():
    v = S[key]
    d = sums(v)
    row = [r for r in rows if r[0] == display]
    expected = [display, '26', '6.0'] + [str(x) for x in d] + [str(round(sum(d), 4)), f"{round(sum(d) / 26 * 100)}%",
                                                                 str(len(fails(v))), tier(len(fails(v)))]
    check(f"Row '{display[:48]}': fields match the vector", len(row) == 1 and row[0][:12] == expected)
    check(f"Builder maps that display name to the key '{key}'", names_map.get(display) == key)
    NOTES[key] = row[0][13] if row else ""
check("Builder name map covers all 23 systems, one-to-one",
      sorted(names_map.values()) == sorted(S) and len(set(names_map)) == 23
      and [r[0] for r in rows[1:]] == list(names_map))

# ---------------------------------------------------------------------------- (4)
print("\n(4) GENERATOR: reproduces both live scripts, and refuses corrupted input")
GEN_INPUTS = [SNAP[CANON][0], SNAP[BUILDER][0], GEN] + [x for k in NEW for x in NEW[k][:3:2]]


def run_generator(corrupt=None):
    with tempfile.TemporaryDirectory() as tmp:
        src, out = os.path.join(tmp, "src"), os.path.join(tmp, "out")
        os.makedirs(src)
        for name in GEN_INPUTS:
            shutil.copy(path(name), src)
        if corrupt:
            name, fn = corrupt
            p = os.path.join(src, name)
            with open(p, encoding="utf-8") as f:
                text = f.read()
            new = fn(text)
            assert new != text, f"negative test did not change {name}"
            with open(p, "w", encoding="utf-8") as f:
                f.write(new)
        proc = subprocess.run([sys.executable, GEN, src, out], cwd=src, capture_output=True)
        produced = {n: open(os.path.join(out, n), "rb").read() for n in (CANON, BUILDER)
                    if os.path.isfile(os.path.join(out, n))}
        return proc, produced


proc, produced = run_generator()
check("Generator runs cleanly on the pinned inputs", proc.returncode == 0)
check("Its canonical-script output is byte-identical to the live file",
      produced.get(CANON) == open(path(CANON), "rb").read())
check("Its CSV-builder output is byte-identical to the live file",
      produced.get(BUILDER) == open(path(BUILDER), "rb").read())


def corrupt_domain_line(text):
    return text.replace("| Material Security | 2.0 | 6 |", "| Material Security | 2.5 | 6 |", 1)


def corrupt_vector(text):
    node = [n for n in ast.parse(text).body if isinstance(n, ast.Assign)
            and any(getattr(t, "id", None) == "OSTROM" for t in n.targets)][0]
    lines = text.split("\n")
    seg = "\n".join(lines[node.lineno - 1:node.end_lineno])
    bad = re.sub(r"""(['"])C5\.5\1: 1\.0""", lambda m: f"{m.group(1)}C5.5{m.group(1)}: 0.5", seg, count=1)
    return text.replace(seg, bad, 1)


NEGATIVE = [
    ("a scratch document's domain line (Islamic finance, Material Security 2.0 -> 2.5)",
     ("NEEC_IslamicFinance_scoring_scratch.md", corrupt_domain_line), "disagrees with the summary stated"),
    ("the pinned snapshot (one byte appended)",
     (SNAP[CANON][0], lambda t: t + "#"), "expected 487d5a94"),
    ("a vector (Ostrom's C5.5 1.0 -> 0.5 in verify_ostrom.py)",
     ("verify_ostrom.py", corrupt_vector), "disagrees with the summary stated"),
]
for label, corrupt, message in NEGATIVE:
    proc, produced = run_generator(corrupt)
    check(f"Refuses corrupted {label}: non-zero exit, named error, no output written",
          proc.returncode != 0 and message in proc.stderr.decode("utf-8") and not produced)

# ---------------------------------------------------------------------------- (5)
print("\n(5) CLAIMS: every claim in the three new row notes and the new `pairs` comment")
N = len(S)
OTHERS = {k: [x for x in S if x != k] for k in S}
T = {k: total(S[k]) for k in S}
F = {k: fails(S[k]) for k in S}
DS = {k: sums(S[k]) for k in S}
PAIRS = [(a, b) for a in S for b in S if a != b and dominates(S[a], S[b])]


def rank(k):
    return 1 + sum(1 for x in S if T[x] > T[k])


def claim(where, text, cond):
    source = NOTES.get(where, where)
    check(f"[{'note' if where in (QA, IF, OS) else 'pairs'}] {text[:112]}", text in source and cond)


LEGACY = list(S)[:13]
FLAG_Q = module_literal(read('verify_qatar.py'), 'FLAGGED')
FLAG_Q = {c: alt for c, (alt, _) in FLAG_Q.items()}
CIT_Q = module_literal(read('verify_qatar.py'), 'CITIZENS_ONLY')
UND_Q = module_literal(read('verify_qatar.py'), 'UNDISPUTED_FAILURES')
FLAG_I = module_literal(read('verify_islamicfinance.py'), 'FLAGGED')
RA_I = module_literal(read('verify_islamicfinance.py'), 'READING_A')
RC_I = module_literal(read('verify_islamicfinance.py'), 'READING_C')
SC_I = module_literal(read('verify_islamicfinance.py'), 'BROAD_SCOPE')
FLAG_O = module_literal(read('verify_ostrom.py'), 'FLAGS')
SC_O = module_literal(read('verify_ostrom.py'), 'SCENARIO')

print("\n  -- State Capitalism / Qatar --")
q = S[QA]
claim(QA, "Ten failures (" + ", ".join(F[QA]) + ")", len(F[QA]) == 10)
und = [c for c in F[QA] if FLAG_Q.get(c, 0.0) == 0.0]
claim(QA, "six undisputed (" + ", ".join(und) + ")", len(und) == 6 and set(und) == UND_Q)
nq, lo, hi, tq = enumerate_flags(q, FLAG_Q)
claim(QA, "The twelve flagged calls are tier-neutral: all 4,096 combinations are Structurally Inadequate "
          "(8.0 to 14.0/26)", len(FLAG_Q) == 12 and nq == 4096 and tq == {'Structurally Inadequate': 4096}
      and (lo, hi) == (8.0, 14.0))
cit = moved(q, CIT_Q)
open_flags = {c: alt for c, alt in FLAG_Q.items() if c not in CIT_Q}
nc, clo, chi, tc = enumerate_flags(cit, open_flags)
claim(QA, "a citizens-only reading changes seven criteria and gives 13.0/26 with 6 failures, still Structurally "
          "Inadequate at the boundary",
      len([c for c in ALL if cit[c] != q[c]]) == 7 and total(cit) == 13.0 and len(fails(cit)) == 6
      and tier(6) == 'Structurally Inadequate' and tier(5) == 'Partially Adequate')
claim(QA, "128 of the 256 combinations of the eight flagged calls it leaves open reach Partially Adequate (12.0 to "
          "16.0/26)", len(open_flags) == 8 and nc == 256 and tc.get('Partially Adequate') == 128
      and 'Potentially Adequate' not in tc and (clo, chi) == (12.0, 16.0))
claim(QA, "Domain 4 (0.5/5) ties State Capitalism / China and Status Quo Market Capitalism for the corpus's lowest",
      DS[QA][3] == 0.5 == min(DS[k][3] for k in S) and {k for k in S if DS[k][3] == 0.5} == {QA, CN, SQ})
claim(QA, "Ranks 22nd of 23, above only Libertarian Minarchism, and ties no system",
      rank(QA) == 22 and N == 23 and [k for k in S if T[k] < T[QA]] == [LM] and [k for k in S if T[k] == T[QA]] == [QA])
claim(QA, "Strictly dominated by exactly two systems -- CCO-PTF-CIP-SZH, and State Capitalism / Singapore "
          "(higher on 10 criteria, lower on none; Singapore's 4 failures are a subset of Qatar's 10) -- and "
          "dominates none",
      sorted(a for a, b in PAIRS if b == QA) == sorted([CCO, SG]) and len(higher(S[SG], q)) == 10
      and not higher(q, S[SG]) and set(F[SG]) <= set(F[QA]) and len(F[SG]) == 4 and not [b for a, b in PAIRS if a == QA])

print("\n  -- Islamic Finance / Profit-Sharing Banking --")
v = S[IF]
claim(IF, "(14.5/26, 4 failures, Partially Adequate)",
      total(moved(v, SC_I)) == 14.5 and len(fails(moved(v, SC_I))) == 4)
claim(IF, "Five failures (" + ", ".join(F[IF]) + ")", len(F[IF]) == 5)
und = [c for c in F[IF] if FLAG_I.get(c, 0.0) == 0.0]
claim(IF, "two undisputed (" + ", ".join(und) + ")", und == ['C2.2', 'C4.2'])
ni, _, _, ti = enumerate_flags(v, FLAG_I)
ra, rc = moved(v, RA_I), moved(v, RC_I)
claim(IF, "Sixteen flagged calls (65,536 combinations); the three coherent joint readings span all three tiers: "
          "A, as designed, 15.5/26 with 2 failures (Potentially Adequate)",
      len(FLAG_I) == 16 and ni == 65536 and total(ra) == 15.5 and len(fails(ra)) == 2
      and len({tier(len(fails(ra))), tier(len(F[IF])), tier(len(fails(rc)))}) == 3)
claim(IF, "C, strict form-over-substance, 10.5/26 with 11 failures (Structurally Inadequate)",
      total(rc) == 10.5 and len(fails(rc)) == 11)
claim(IF, "Domain 5 (4.5/5) equals CCO-PTF-CIP-SZH's, the corpus's highest, and no other system reaches it",
      DS[IF][4] == DS[CCO][4] == 4.5 == max(DS[k][4] for k in S) and {k for k in S if DS[k][4] == 4.5} == {IF, CCO})
gap = {k: DS[k][4] - DS[k][3] for k in S}
claim(IF, "its Domain 5 minus Domain 4 gap (3.0) is the corpus's second-widest, behind Status Quo Market "
          "Capitalism (3.5)",
      gap[IF] == 3.0 and gap[SQ] == 3.5 and [k for k in S if gap[k] >= 3.0] == [SQ, IF])
c55 = [k for k in S if S[k]['C5.5'] == 1.0]
claim(IF, "Joint-best C5.5 (1.0), with Participatory Economics, Mutual Credit / LETS, and Ostrom-Style Commons "
          "Governance", c55 == [PE, MC, IF, OS] and max(S[k]['C5.5'] for k in S) == 1.0)
claim(IF, "Exact three-way tie at 13.5/26 with Georgism / Land Value Tax and Universal Basic Services, spanning "
          "two tiers (2, 3, and 5 failures); rank 13 of 23",
      [k for k in S if T[k] == 13.5] == [GEO, UBS, IF] and [len(F[k]) for k in (GEO, UBS, IF)] == [2, 3, 5]
      and len({tier(len(F[k])) for k in (GEO, UBS, IF)}) == 2 and rank(IF) == 13)
claim(IF, "Strictly dominates Stakeholder Capitalism alone (higher on 6 criteria, lower on none), the only Step 1b "
          "entry to dominate one of the 13 legacy systems",
      [b for a, b in PAIRS if a == IF] == [STK] and len(higher(v, S[STK])) == 6 and not higher(S[STK], v)
      and {a for a, b in PAIRS if a in STEP1B and b in LEGACY} == {IF} and len(LEGACY) == 13 and LEGACY[-1] == 'Integral')
claim(IF, "Dominated by no system, CCO-PTF-CIP-SZH included: it exceeds CCO-PTF-CIP-SZH on C5.5 alone",
      not [a for a, b in PAIRS if b == IF] and higher(v, S[CCO]) == ['C5.5'])

print("\n  -- Ostrom-Style Commons Governance --")
o = S[OS]
claim(OS, "scored as a scope scenario (15.0/26, 3 failures, Partially Adequate)",
      total(moved(o, SC_O)) == 15.0 and len(fails(moved(o, SC_O))) == 3)
claim(OS, "Four failures (" + ", ".join(F[OS]) + "), none undisputed: each has a stated alternative that removes it",
      len(F[OS]) == 4 and all(FLAG_O.get(c, 0.0) > 0.0 for c in F[OS]))
no, olo, ohi, to = enumerate_flags(o, FLAG_O)
up = moved(o, {c: a for c, a in FLAG_O.items() if a > o[c]})
down = moved(o, {c: a for c, a in FLAG_O.items() if a < o[c]})
claim(OS, "Twenty flagged calls (1,048,576 combinations) span 9.5 to 19.5/26 and all three tiers",
      len(FLAG_O) == 20 and no == 1048576 and (olo, ohi) == (9.5, 19.5) and len(to) == 3)
claim(OS, "A (the long-enduring case: 19.5/26, 0 failures, Potentially Adequate) and C (strict population scope: "
          "9.5/26, 11 failures, Structurally Inadequate) are exactly the enumeration's extremes",
      (total(up), len(fails(up)), total(down), len(fails(down))) == (19.5, 0, 9.5, 11) and (olo, ohi) == (9.5, 19.5))
claim(OS, "it is the only system in the corpus at 0.0 on C3.2", [k for k in S if S[k]['C3.2'] == 0.0] == [OS])
claim(OS, "Joint-best C5.5 (1.0).", o['C5.5'] == 1.0 == max(S[k]['C5.5'] for k in S))
claim(OS, "Domain 5 (4.0/5) is beaten only by CCO-PTF-CIP-SZH and Islamic Finance / Profit-Sharing Banking (4.5 each)",
      DS[OS][4] == 4.0 and [k for k in S if DS[k][4] > 4.0] == [CCO, IF])
claim(OS, "Domain 1 (2.0/6) is below 14 of the other 22 systems",
      DS[OS][0] == 2.0 and sum(1 for k in OTHERS[OS] if DS[k][0] > 2.0) == 14)
claim(OS, "Exact three-way tie at 14.0/26 with Sovereign Wealth Fund Statism and State Capitalism / Singapore, all "
          "Partially Adequate (3, 4, and 4 failures)",
      [k for k in S if T[k] == 14.0] == [SWF, SG, OS] and [len(F[k]) for k in (SWF, SG, OS)] == [3, 4, 4])
claim(OS, "Dominated by no system, CCO-PTF-CIP-SZH included (it exceeds CCO-PTF-CIP-SZH on C5.5 alone), and "
          "dominates none",
      not [p for p in PAIRS if OS in p] and higher(o, S[CCO]) == ['C5.5'])

print("\n  -- The new `pairs` comment in the canonical script --")
text = read(CANON)
start = text.index("        # Session 25 additions.")
block = text[start:text.index("        (", start)]
COMMENT = " ".join(line.strip()[2:] for line in block.strip().split("\n"))
NOTES[COMMENT] = COMMENT
ESC = {k: higher(S[k], S[CCO]) for k in S if k != CCO and not dominates(S[CCO], S[k])}
claim(COMMENT, "Islamic Finance / Profit-Sharing Banking ties Georgism and UBS exactly (13.5/26)",
      T[IF] == T[GEO] == T[UBS] == 13.5)
claim(COMMENT, "Ostrom-Style Commons Governance ties SWF Statism and Singapore exactly (14.0/26)",
      T[OS] == T[SWF] == T[SG] == 14.0)
claim(COMMENT, "so none of those four pairs can be a dominance relation",
      not [p for p in PAIRS if set(p) in ({IF, GEO}, {IF, UBS}, {OS, SWF}, {OS, SG})])
claim(COMMENT, "Islamic finance strictly dominates Stakeholder Capitalism, and Singapore strictly dominates Qatar",
      (IF, STK) in PAIRS and (SG, QA) in PAIRS)
claim(COMMENT, "Islamic finance and Ostrom dominate neither way (they differ on 9 criteria), and China does not "
          "dominate Qatar",
      (IF, OS) not in PAIRS and (OS, IF) not in PAIRS and len(higher(S[IF], o) + higher(o, S[IF])) == 9
      and (CN, QA) not in PAIRS)
claim(COMMENT, "CCO-PTF-CIP-SZH dominates Qatar but neither of the other two",
      (CCO, QA) in PAIRS and (CCO, IF) not in PAIRS and (CCO, OS) not in PAIRS)
claim(COMMENT, "it scores 1.0 on 23 criteria and 0.5 on C1.5, C4.5, and C5.5",
      [c for c in ALL if S[CCO][c] != 1.0] == ['C1.5', 'C4.5', 'C5.5'] and all(S[CCO][c] == 0.5 for c in ('C1.5', 'C4.5', 'C5.5')))
claim(COMMENT, "each of the 11 systems it does not dominate -- these two included -- exceeds it on exactly one of "
          "those three (both of these on C5.5)",
      len(ESC) == 11 and all(len(x) == 1 and x[0] in ('C1.5', 'C4.5', 'C5.5') for x in ESC.values())
      and ESC[IF] == ESC[OS] == ['C5.5'])
FRONTIER = [k for k in S if not any(dominates(S[a], S[k]) for a in S if a != k)]
claim(COMMENT, "Every system dominated by any system is also dominated by CCO-PTF-CIP-SZH, so the Pareto frontier is "
          "exactly CCO-PTF-CIP-SZH plus those 11 (12 systems)",
      {b for _, b in PAIRS} == {b for a, b in PAIRS if a == CCO} and FRONTIER == [k for k in S if k == CCO or k in ESC]
      and len(FRONTIER) == 12)

# ---------------------------------------------------------------------------- (6)
print("\n(6) STEP 5 REFERENCE FACTS: the combined 23-system corpus")
EXPECTED_RANKS = [  # (key, competition rank, total, failures) in the Session 24 handoff's order
    (CCO, 1, 24.5, 0), (PE, 2, 20.5, 1), ('Nordic Social Democracy', 3, 19.5, 2), ('Integral', 3, 19.5, 3),
    ('Degrowth Economics', 5, 19.0, 2), ('Market Socialism', 6, 16.5, 2), ('MMT + Job Guarantee', 7, 15.5, 3),
    ('Universal Basic Income', 8, 14.5, 7), (MC, 8, 14.5, 3), (SWF, 10, 14.0, 3), (SG, 10, 14.0, 4), (OS, 10, 14.0, 4),
    (GEO, 13, 13.5, 2), (UBS, 13, 13.5, 3), (IF, 13, 13.5, 5), ('Fully Automated Luxury Communism', 16, 13.0, 10),
    ('Doughnut Economics', 17, 11.5, 8), (SQ, 18, 10.5, 9), ('Centrally Planned Socialism', 19, 10.0, 12),
    (STK, 19, 10.0, 9), (CN, 19, 10.0, 8), (QA, 22, 9.0, 10), (LM, 23, 8.0, 15)]
ORDER = sorted(S, key=lambda k: (-T[k], list(S).index(k)))
check("Ranking (competition ranks, totals, failures) equals the Session 24 handoff's combined table",
      [(k, rank(k), T[k], len(F[k])) for k in ORDER] == EXPECTED_RANKS)
TIERS = {t: [k for k in S if tier(len(F[k])) == t] for t in ('Potentially Adequate', 'Partially Adequate',
                                                            'Structurally Inadequate')}
check("Tier counts 6 / 8 / 9 (Session 20: 6 / 6 / 8)", [len(x) for x in TIERS.values()] == [6, 8, 9])
TIES = {}
for k in S:
    TIES.setdefault(T[k], []).append(k)
TIES = {t: ks for t, ks in TIES.items() if len(ks) > 1}
TIED_PAIRS = [p for ks in TIES.values() for p in combinations(ks, 2)]
check("Tie groups: 19.5 (2), 14.5 (2), 14.0 (3, one tier), 13.5 (3, two tiers), 10.0 (3); 11 tied pairs; "
      "Qatar ties nothing",
      {t: len(ks) for t, ks in TIES.items()} == {19.5: 2, 14.5: 2, 14.0: 3, 13.5: 3, 10.0: 3} and len(TIED_PAIRS) == 11
      and len({tier(len(F[k])) for k in TIES[14.0]}) == 1 and len({tier(len(F[k])) for k in TIES[13.5]}) == 2
      and QA not in {k for ks in TIES.values() for k in ks})
check("14 dominance pairs: CCO-PTF-CIP-SZH over 11; Singapore over China and Qatar; IF over Stakeholder",
      len(PAIRS) == 14 and len([p for p in PAIRS if p[0] == CCO]) == 11
      and sorted(p for p in PAIRS if p[0] != CCO) == sorted([(SG, CN), (SG, QA), (IF, STK)]))
check("CCO-PTF-CIP-SZH escape table: C1.5 {Nordic}; C4.5 {CPS, Libertarian Minarchism, UBI, Degrowth, FALC, "
      "Integral}; C5.5 {ParEcon, Mutual Credit / LETS, IF, Ostrom}",
      {c: sorted(k for k, x in ESC.items() if x == [c]) for c in ('C1.5', 'C4.5', 'C5.5')} ==
      {'C1.5': ['Nordic Social Democracy'],
       'C4.5': sorted(['Centrally Planned Socialism', LM, 'Universal Basic Income', 'Degrowth Economics',
                       'Fully Automated Luxury Communism', 'Integral']),
       'C5.5': sorted([PE, MC, IF, OS])})
check("Pareto frontier 10 -> 12: the Session 20 frontier plus IF and Ostrom; Qatar is not on it",
      [k for k in FRONTIER if k not in (IF, OS)] == [k for k in s20.SCORES
                                                     if not any(dominates(s20.SCORES[a], s20.SCORES[k])
                                                                for a in s20.SCORES if a != k)]
      and len(FRONTIER) == 12 and IF in FRONTIER and OS in FRONTIER and QA not in FRONTIER)
check("New entries against each other: IF vs Ostrom differ on 9 (IF higher on 4, Ostrom on 5, Ostrom +0.5); "
      "Qatar vs IF differ on 12 (Qatar higher on 2); Qatar vs Ostrom differ on 13 (Qatar higher on 2)",
      (len(higher(S[IF], o)), len(higher(o, S[IF])), T[OS] - T[IF]) == (4, 5, 0.5)
      and (len(higher(q, S[IF])) + len(higher(S[IF], q)), len(higher(q, S[IF]))) == (12, 2)
      and (len(higher(q, o)) + len(higher(o, q)), len(higher(q, o))) == (13, 2))
check("Ostrom vs Georgism: differ on 5 criteria, Ostrom +0.5",
      len(higher(o, S[GEO]) + higher(S[GEO], o)) == 5 and T[OS] - T[GEO] == 0.5)
check("Domain 5 below the 4.5 pair: Status Quo, Nordic, Mutual Credit / LETS, Ostrom at 4.0",
      sorted(k for k in S if DS[k][4] == 4.0) == sorted([SQ, 'Nordic Social Democracy', MC, OS]))
check("Domain 4 bottom: 0.5 {China, Qatar, Status Quo}; 1.0 {Stakeholder, Singapore}; 1.5 {IF, Libertarian "
      "Minarchism}",
      {x: sorted(k for k in S if DS[k][3] == x) for x in (0.5, 1.0, 1.5)} ==
      {0.5: sorted([CN, QA, SQ]), 1.0: sorted([STK, SG]), 1.5: sorted([IF, LM])})
print("\n  -- Corrections found by reading in Session 24, asserted so they cannot recur --")
check("IF's Domain 5 minus Domain 4 gap is second-widest, not widest (Status Quo 3.5, IF 3.0, then China, "
      "Singapore and Qatar 2.5) -- already false against the 20-system corpus",
      sorted(gap.values(), reverse=True)[:5] == [3.5, 3.0, 2.5, 2.5, 2.5]
      and sorted(k for k in S if gap[k] == 2.5) == sorted([CN, SG, QA])
      and max(v2 for k, v2 in gap.items() if k in s20.SCORES) == 3.5)
check("'The only Step 1b entry to dominate an existing system' is false: Singapore (Step 1b) dominates China and "
      "Qatar; IF is the only Step 1b entry that dominates one of the 13 legacy systems",
      (SG, CN) in PAIRS and (SG, QA) in PAIRS and {a for a, b in PAIRS if a in STEP1B and b in LEGACY} == {IF})
check("Ostrom's C5.5 is joint-best, not best-in-corpus (shared with ParEcon, Mutual Credit / LETS, and IF)",
      c55 == [PE, MC, IF, OS])

# ---------------------------------------------------------------------------- tables
print("\n" + "=" * 96)
print("STEP 5 REFERENCE TABLES (23 systems; generated from the live canonical script)")
print("=" * 96)
print("\nRanking (equal weighting; competition ranks, ties marked '='):")
for k in ORDER:
    r = rank(k)
    mark = "=" if sum(1 for x in S if T[x] == T[k]) > 1 else " "
    print(f"  {r:>2}{mark} {k:<42} {T[k]:5.1f}/26 {T[k] / 26 * 100:5.1f}%  {len(F[k]):>2} failure{'s' if len(F[k]) != 1 else ' '}  {tier(len(F[k]))}")
print("\nDomain excellence (top five per domain; ties at the cut-off included):")
for i, name in enumerate(DOMAIN_NAMES):
    cut = sorted((DS[k][i] for k in S), reverse=True)[4]
    top = sorted((k for k in S if DS[k][i] >= cut), key=lambda k: (-DS[k][i], list(S).index(k)))
    print(f"  D{i + 1} {name}: " + "; ".join(f"{k} {DS[k][i]:.1f}" for k in top))
print("\nCriterion-level failure counts (systems at 0.0):")
counts = [(c, sum(1 for k in S if S[k][c] == 0.0)) for c in ALL]
for i in range(0, len(counts), 6):
    print("  " + "   ".join(f"{c:<5} {n:>2}" for c, n in counts[i:i + 6]))
print("\nCCO-PTF-CIP-SZH escape table (the 11 systems it does not dominate, and the one criterion each wins):")
for c in ('C1.5', 'C4.5', 'C5.5'):
    print(f"  {c}: " + ", ".join(k for k in ESC if ESC[k] == [c]))
print("\nDominance pairs (14):")
for a, b in PAIRS:
    print(f"  {a}  >  {b}")
print("\nPareto frontier (12): " + ", ".join(FRONTIER))

# ---------------------------------------------------------------------------- summary
print("\n" + "=" * 96)
n_pass = sum(RESULTS)
print(f"SUMMARY: {n_pass} passed, {len(RESULTS) - n_pass} failed (of {len(RESULTS)}).")
print("=" * 96)
sys.exit(0 if all(RESULTS) else 1)
